### ISSUE TITLE
No way to assign data_base64 attribute

### ISSUE THREAD

**Issue by oising** [cloudevents/sdk-csharp#302]
As there is no first class support for setting data_base64 (i.e. binary data), I attempted to set it using `SetAttributeFromString("data_base64", "<BASE64>")` and this yielded a validation error at runtime from `Validate()` complaining that the underscore is not a valid character:

```text
== APP - subscriber == Unhandled exception. System.ArgumentException: Invalid character '_' in attribute name 'data_base64' (Parameter 'name')
== APP - subscriber ==    at CloudNative.CloudEvents.CloudEventAttribute.ValidateName(String name)
== APP - subscriber ==    at CloudNative.CloudEvents.CloudEventAttribute..ctor(String name, CloudEventAttributeType type, Boolean required, Boolean extension, Action`1 validator)
== APP - subscriber ==    at CloudNative.CloudEvents.CloudEventAttribute.CreateExtension(String name, CloudEventAttributeType type)
== APP - subscriber ==    at CloudNative.CloudEvents.CloudEvent.set_Item(String attributeName, Object value)
== APP - subscriber ==    at CloudNative.CloudEvents.CloudEvent.SetAttributeFromString(String name, String value)
```
(stacktrace from DAPR)

See: https://github.com/cloudevents/spec/blob/main/cloudevents/formats/json-format.md#311-payload-serialization

**Comment by jskeet** [comment]
At the CloudEvent level, there's just data - whether it's represented as base64 or not depends on the format. If you just set the data to binary data, then most formats (not all) will use base64 to represent it.

**Comment by oising** [comment]
> At the CloudEvent level, there's just data - whether it's represented as base64 or not depends on the format. If you just set the data to binary data, then most formats (not all) will use base64 to represent it.

I'm not following you. Section 3.1.1 of json-formats seems clear:

"If the implementation determines that the type of data is Binary, the value MUST be represented as a [JSON string](https://tools.ietf.org/html/rfc7159#section-7) expression containing the [Base64](https://tools.ietf.org/html/rfc4648#section-4) encoded binary value, and use the member name data_base64 to store it inside the JSON representation. If present, the datacontenttype MUST reflect the format of the original binary data."

I'm testing the middleware to see if it will decode the base64 and forward an unwrapped message that is declared to be base64 encoded json (which is a binary stream of utf8 bytes)
i.e.

I'm sending this CE (raw, via httpclient):

```json
{
    "specversion" : "1.0",
    "type": "com.example.myevent",
    "source": "urn:example-com:mysource",
    "time" : "2018-04-05T17:31:00Z",
    "id": "A234-1234-1234",
    "datacontenttype" : "application/json",
    "data_base64" : "eyAiZm9vIjoiYmFyIiB9"
}
```
to:

```csharp
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

// Dapr will send serialized event object vs. being raw CloudEvent
app.UseCloudEvents();

// needed for Dapr pub/sub routing
app.MapSubscribeHandler();

if (app.Environment.IsDevelopment()) { app.UseDeveloperExceptionPage(); }

app.MapPost("/message", [Topic("binpubsub", "message")] (JsonElement json) => {
    Console.WriteLine("Subscriber received : " + json);
    return Results.Ok(json);
});

await app.RunAsync();
```

and this gets transformed by the middleware to:

```json
{ "foo": "bar" }
```

**This works as expected**, although I wasn't expected JsonElement (I thought it might be string, but hey, I'm fine with this.)

So, my problem is that the SDK does not let me programmatically construct the message I'm currently creating by hand.

**Comment by jskeet** [comment]
I'll look at this tomorrow (UK time) if I have the time. It's not clear to me at the moment what you're trying to do that the SDK won't "let you" do. If it's that you want to be able to create a `CloudEvent` which ends up serialized as the JSON you've provided, you absolutely can do that (this is using the System.Text.Json serializer, but I expect the Json.NET one will do the same thing):

```csharp
using CloudNative.CloudEvents;
using CloudNative.CloudEvents.SystemTextJson;
using System.Text;

var evt = new CloudEvent
{
    Type = "com.example.myevent",
    Source = new Uri("urn:example-com:mysource", UriKind.RelativeOrAbsolute),
    Time = new DateTimeOffset(2018, 4, 5, 17, 31, 0, TimeSpan.Zero),
    Id = "A234-1234-1234",
    DataContentType = "application/json",
    // We want the JSON to be represented as base64 (which is
    // odd, given that it's textual data) so we need Data to
    // be a byte array.
    Data = Convert.FromBase64String("eyAiZm9vIjoiYmFyIiB9")
};

// Serialize the CloudEvent as JSON.
var formatter = new JsonEventFormatter();
var memory = formatter.EncodeStructuredModeMessage(evt, out var contentType);
var text = Encoding.UTF8.GetString(memory.Span);

// Print out the serialized results.
Console.WriteLine(text);
```

Output:

```json
{"specversion":"1.0","type":"com.example.myevent","source":"urn:example-com:mysource","time":"2018-04-05T17:31:00Z","id":"A234-1234-1234","datacontenttype":"application/json","data_base64":"eyAiZm9vIjoiYmFyIiB9"}
```

**Comment by oising** [comment]
Ah! It's the serializer that does the magic. Ok, now I understand. Thanks Jon. While i was waiting for your answer, I migrated this repo to centralized package management as a thank you lol 

https://github.com/cloudevents/sdk-csharp/pull/303

**Comment by jskeet** [comment]
Are you happy for us to close this now, or is there another aspect we should look at?

**Comment by oising** [comment]
No longer an issue, closing.
